name: rup
channels:
  - conda-forge
  - bioconda
  - nodefaults
  - defaults
dependencies:
  - bioconductor-rfastp
  - bioconductor-rsubread
  - bioconductor-rsamtools
  - r-fastqcr
  - r-getopt
  - r-ggplot2
  - r-pheatmap
  - r-reshape2
